# Generated by Django 5.1.6 on 2025-02-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(help_text='Race du cheval', max_length=100)),
                ('trainer', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.IntegerField(help_text="Nombre d'années d'expérience")),
                ('win_percentage', models.FloatField(help_text='Pourcentage de victoires')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('distance', models.IntegerField(help_text='Distance en mètres')),
                ('terrain', models.CharField(choices=[('herbe', 'Herbe'), ('sable', 'Sable'), ('boue', 'Boue')], max_length=50)),
                ('weather', models.CharField(help_text='Conditions météo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('time', models.FloatField(help_text='Temps réalisé en secondes')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.horse')),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.jockey')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
            options={
                'unique_together': {('race', 'horse')},
            },
        ),
    ]
