# Generated by Django 5.1.6 on 2025-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(help_text='Critère analysé', max_length=100)),
                ('selection_count', models.IntegerField(default=0, help_text='Nombre de fois utilisé')),
            ],
        ),
    ]
