# Generated by Django 5.1.6 on 2025-02-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('simple_gagnant', 'Simple Gagnant'), ('simple_place', 'Simple Placé'), ('tierce', 'Tiercé'), ('quarte', 'Quarté'), ('quinte', 'Quinté')], max_length=50)),
                ('amount', models.FloatField(help_text='Montant misé (simulation)')),
                ('potential_gain', models.FloatField(default=0.0, help_text='Gain potentiel simulé')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
                ('selected_horses', models.ManyToManyField(to='races.horse')),
            ],
        ),
    ]
